version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/
    command: "npm run start:dev"
    ports:
      - 8000:3000
    volumes:
      - ./api-gateway/:/app
    networks:
      - pfa

  appointment:
    container_name: appointment
    build:
      context: ./appointment/
    command: "npm run start:dev"
    ports:
      - 8001:3000
    volumes:
      - ./appointment/:/app
    networks:
      - pfa

  auth:
    container_name: auth
    build:
      context: ./auth/
    command: "npm run start:dev"
    ports:
      - 8002:3000
    volumes:
      - ./auth/:/app
    networks:
      - pfa

  chat:
    container_name: chat
    build:
      context: ./chat/
    command: "npm run start:dev"
    ports:
      - 8003:3000
    volumes:
      - ./chat/:/app
    networks:
      - pfa

networks:
  pfa:
