version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/
    command: "npm run start:dev"
    ports:
      - 8000:3000
    volumes:
      - ./api-gateway/:/app
    networks:
      - pfa

  appointment:
    container_name: appointment
    build:
      context: ./appointment/
    command: "npm run start:dev"
    ports:
      - 8001:3001
    volumes:
      - ./appointment/:/app
    networks:
      - pfa

  auth:
    container_name: auth
    build:
      context: ./auth/
    command: "npm run start:dev"
    ports:
      - 8002:3001
    volumes:
      - ./auth/:/app
    networks:
      - pfa

  chat:
    container_name: chat
    build:
      context: ./chat/
    command: "npm run start:dev"
    ports:
      - 8003:3001
    volumes:
      - ./chat/:/app
    networks:
      - pfa

  rabbitmq:
    # default username and password are 'guest'
    container_name: rabbitmq
    image: rabbitmq:3.9.15-management-alpine
    ports:
      - "5672:5672" # Port for microservices applicaiton to connect to
      - "15672:15672" # Port for management UI interface
    volumes:
      - rabbitmqPfaData:/var/lib/rabbitmq/
      - rabbitmqPfaLog:/var/log/rabbitmq
    networks:
      - pfa

networks:
  pfa:

volumes:
  rabbitmqPfaData:
  rabbitmqPfaLog:
