apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-mongodb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-mongodb
  template:
    metadata:
      labels:
        app: appointment-mongodb
    spec:
      containers:
        - name: appointment-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: appointments
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-mongodb-srv
spec:
  type: ClusterIP
  selector:
    app: appointment-mongodb
  ports:
    - name: appointment-mongodb
      protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #pod port

