apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: mahdibouaziz/appointment
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: DATABASE_PASSWORD

            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: APPOINTMENT_DATABASE_NAME

            - name: DATABASE_TEST_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: APPOINTMENT_DATABASE_TEST_NAME

            - name: DATABASE_LINK
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: APPOINTMENT_DATABASE_LINK

            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_USER

            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_PASSWORD

            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_HOST

            - name: RABBITMQ_AUTH_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_AUTH_QUEUE_NAME

            - name: RABBITMQ_APPOINTMENT_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: RABBITMQ_APPOINTMENT_QUEUE_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-srv
spec:
  type: ClusterIP
  selector:
    app: appointment
  ports:
    - name: appointment
      protocol: TCP
      port: 3000 #service port
      targetPort: 3000 #pod port
