apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-mongo-express-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-mongo-express
  template:
    metadata:
      labels:
        app: appointment-mongo-express
    spec:
      containers:
        - name: appointment-mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: appointment-mongodb-srv
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: admin
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: admin
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: admin

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-mongo-exress-srv
spec:
  type: NodePort
  selector:
    app: appointment-mongo-express
  ports:
    - name: appointment-mongo-express
      protocol: TCP
      port: 8081 #service port
      targetPort: 8081 #pod port
      nodePort: 30001
