apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: mahdibouaziz/appointment
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-srv
spec:
  type: ClusterIP
  selector:
    app: appointment
  ports:
    - name: appointment
      protocol: TCP
      port: 3000 #service port
      targetPort: 3000 #pod port
